### ISSUE TITLE
编译后运行会报三种错

### ISSUE THREAD

**Issue by junmaqiang** [lifei6671/DouYinBot#3]
# 解决方案如下
① ./admin/app.conf.example 要改为 ./admin/conf/app.conf
② 要给app.conf里面的 auto-save-path 设置一个路径
③ 要手动创建一个数据库文件 ./data/douyinbot.db 

# 经过上面的三条修改，最后能跑起来
但是解析似乎规则有调整，因此也会报错。
类似抖音升级后，也要跟着改。

**Comment by junmaqiang** [comment]
# 报解析的错
![截屏2023-09-24 22 24 14](https://github.com/lifei6671/DouYinBot/assets/1819457/3884a20a-869d-4138-95e4-d83fca6574b1)

**Comment by lifei6671** [comment]
嗯，后面会切换解析方法，抖音的接口签名变动太频繁。
